server:
  address: localhost
  port: 9000
  compression:
    enabled: true
  http2:
    enabled: true

  error:
    whitelabel:
      enabled: false

#  tomcat:
#    basedir:

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test8_001?characterEncoding=utf8&serverTimezone=UTC
    username: ${datasource.username}
    password: ${datasource.password}
    properties:
      database: test8_001
      serverTimezone: UTC
    pool:
      enabled: true

  data:
    r2dbc:
      repositories:
        enabled: true

  profiles:
    active: "dev"

  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3306/test8_001?characterEncoding=utf8&serverTimezone=UTC
    user: ${datasource.username}
    password: ${datasource.password}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - openid
              - profile
              - email
#            clientAuthenticationScheme: form
#            accessTokenUri: "https://www.googleapis.com/oauth2/v4/token"
#            userAuthorizationUri: "https://accounts.google.com/o/oauth2/v2/auth"
#            resource:
#              userInfoUri: "https://wwwgoogleapiscom/oauth2/v3/userinfo"
#              preferTokenInfo: true

          github:
            client-id: ${github.client-id}
            client-secret: ${github.client-secret}

  mail:
    protocol: smtp
    host: "smtp.yandex.ru"
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: "UTF-8"
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
#      включаем css и проч.
      add-mappings: true
      cache:
        cachecontrol:
          no-cache: true
        period: 0
      chain:
        cache: false
      static-locations: classpath:/resources/

  thymeleaf:
    render-hidden-markers-before-checkboxes: true
    cache: false
    mode: HTML
    reactive:
     max-chunk-size: 8192

#  mustache:
#    enabled: true
#    cache: false
#    prefix: classpath:/templates/

  devtools:
    restart:
      enabled: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data:
          r2dbc: DEBUG

jwt:
  header: "Authorization"
  secret: "auth-secret-very-very-very-very-very-very-very-very-3600000-86400000"
  expiration: 3600000
  refresh: 86400000
  ## For test
#  expiration: 60000
#  refresh: 120000

springfox:
  documentation:
    swagger-ui:
      enabled: true
#      base-url: /swagger-ui/
